### ISSUE TITLE
DockerComposeEnvironment Does not start (Error: Port 2888 not bound after 60000ms)

### ISSUE THREAD

**Issue by flolu** [testcontainers/testcontainers-node#109]
``` typescript
const path = require('path');
const {DockerComposeEnvironment} = require('testcontainers');

(async () => {
  const composeFilePath = path.resolve(__dirname, '../../');
  const composeFile = 'docker-compose.yaml';
  console.log('start');
  const environment = await new DockerComposeEnvironment(composeFilePath, composeFile).up();
  console.log('up');
  await environment.down();
})();
```

```yaml
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
```

The `docker-compose.yaml` file works fine when running it via `docker-compose up`.
But the the code snippet above throws an error:

```
start
(node:210678) UnhandledPromiseRejectionWarning: Error: Port 2888 not bound after 60000ms
    at retryStrategy.retryUntil (/home/flolu/Desktop/centsideas/node_modules/testcontainers/dist/wait-strategy.js:61:23)
    at IntervalRetryStrategy.<anonymous> (/home/flolu/Desktop/centsideas/node_modules/testcontainers/dist/retry-strategy.js:37:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/flolu/Desktop/centsideas/node_modules/testcontainers/dist/retry-strategy.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
