### ISSUE TITLE
Docker Compose for Node not properly finishing the spinup

### ISSUE THREAD

**Issue by aixellent** [testcontainers/testcontainers-node#133]
I tried to spin up my Testsetup in my globalSetup file (JEST) with the following docker-compose.yml:
```
version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    volumes:
      - './rabbitmq/etc/:/etc/rabbitmq/'
      - './rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json:ro'
    ports:
      - 5672
      - 15672
      - 25672
  api:
    image: gcr.io/gke-utility/mocks
    container_name: api
    ports:
      - 5000
    command: api/v1.yaml
```

This is just to ensure my dependencies for the service i want to Test.

Global Setup file
```
import { Duration, TemporalUnit } from 'node-duration'
import { DockerComposeEnvironment, StartedTestContainer } from 'testcontainers'
import path = require('path')

export default async (): Promise<void> => {
  const composeFilePath: string = path.basename('../.docker')
  const composeFile = 'docker-compose.yml'
  const environment = await new DockerComposeEnvironment(composeFilePath, composeFile)
    .withStartupTimeout(new Duration(200, TemporalUnit.SECONDS))
    .up()

  const rabbitmq: StartedTestContainer = environment.getContainer('rabbitmq')
  const bully: StartedTestContainer = environment.getContainer('bully')

  // THE REST OF THE SETUP

}
```

The following problem occurs after the timeout:

`
$ NODE_ENV=test jest --config=__integration-tests__/jest.config.js --testRunner='jest-circus/runner' --ci --verbose --maxWorkers=7
Error: Port 5671 not bound after 200000ms
    at /PATH_TO_PROJECT/node_modules/testcontainers/dist/wait-strategy.js:61:23
    at IntervalRetryStrategy.<anonymous> /PATH_TO_PROJECT/node_modules/testcontainers/dist/retry-strategy.js:37:28)
    at Generator.next (<anonymous>)
    at fulfilled (/PATH_TO_PROJECT/testcontainers/dist/retry-strategy.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

The problem occurs on binding the service Ports, for RabbitMQ, additionally 

Project structure of the IT:
![image](https://user-images.githubusercontent.com/11715453/93633381-303c9c80-f9ef-11ea-9a5d-f041b1e906f3.png)

The two containers are started properly (see container Overview here)
 
![image](https://user-images.githubusercontent.com/11715453/93635136-1781b600-f9f2-11ea-941f-18cd269fcc40.png)

What can i do to get to get this running properly, i would love to use this for the service dependency configuration, especially because the rabbitMQ Preconfiguration over definitions.json would be awesome.
