### ISSUE TITLE
Error: Port XXX not bound after 10000ms  docker-compose -rabbitmq

### ISSUE THREAD

**Issue by johnico** [testcontainers/testcontainers-node#149]
Hello,  I am trying to create a docker-compose file with rabbitmq service but got the following error:

**Error: Port 15691 not bound after 10000ms**

evreytime with diffrent port

my docker -compose
```
version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "1234:5672" 
```

my code 

```
  environment = await new DockerComposeEnvironment('./test/', composeFile)
      .withStartupTimeout(new Duration(10, TemporalUnit.SECONDS))
      .up();
```

thanks
