### ISSUE TITLE
docker-compose with network alias / DNS override

### ISSUE THREAD

**Issue by enote-kane** [testcontainers/testcontainers-node#337]
I have a container in a docker-compose setup that replaces a well-known server (which is hard-coded in a dependency) to provide a "mock" server instead.

Now the only way to do this is using network aliases:
```yaml
networks:
  test:

services:
  external-server-mock:
    ...
    networks:
      test:
        aliases:
          - official.host.org
```

So, how can I "attach" the test execution to the network so that its DNS resolution correctly points to the desired mock container?
