### ISSUE TITLE
Running testcontainers-node inside a docker container

### ISSUE THREAD

**Issue by viswanr** [testcontainers/testcontainers-node#491]
I have been following the instructions on the testcontainers java page to run some tests using Jest inside a docker container. The test setup up's and down's a docker compose environment using testcontainers-node. I have set up the socket connection etc so that the container running testcontainers can speak to the host docker desktop on Windows. But I can't get this to work. Is this even supported in the node version of testcontainers? Note: I have had to disable RYUK as it's not within the safe registry that the organization uses. I'm still able to run everything on a host machine, but the problem is when I try to run testcontainers itself inside docker. Do i have to install docker-compose inside the environment? I thought testcontainers would be able to talk to the host docker desktop which already contains docker-compose.

I'm using the node16-alpine image and running my tests inside that container. 
**Expected Behaviour**
... The environment goes up and the tests continue to run

**Actual Behaviour**
... spawn docker-compose ENOENT
2023-03-10 13:28:49 
2023-03-10 13:28:49       at node_modules/testcontainers/dist/docker-compose/functions/docker-compose-up.js:37:15
2023-03-10 13:28:49           at Generator.throw (<anonymous>)
2023-03-10 13:28:49       at rejected (node_modules/testcontainers/dist/docker-compose/functions/docker-compose-up.js:6:65)

**Testcontainer Logs**
...testcontainers INFO  Starting DockerCompose environment: testcontainers-811aba12c6ae9b8163ddaa188f2c82c0 +0ms
  testcontainers DEBUG Not creating new Reaper for session: 985c5918b7a7a5889f46a2a775bff403 +1ms
  testcontainers INFO  Upping DockerCompose environment +1ms
  testcontainers ERROR Failed to up DockerCompose environment: spawn docker-compose ENOENT +34ms
  testcontainers INFO  Downing DockerCompose environment +1ms
  testcontainers ERROR Failed to down DockerCompose environment: spawn docker-compose ENOENT +39ms
  testcontainers WARN  Failed to down DockerCompose environment after failed up +1ms

**Steps to Reproduce**
1. In this environment... alpine linux image with node and yarn
2. With this config... 
```
services:
  testrunner:
    container_name: testrunner
    hostname: testrunner
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Link in your current .npmrc into the container for access to packages
      - ~/.npmrc:/root/.npmrc:ro
    command: sleep infinity
```
Dockerfile
```
FROM node:16.19-alpine

WORKDIR /home/site/wwwroot

COPY package.json jest.config.ts tsconfig.common.json yarn.lock babel.config.js docker-compose.yml .npmrc ./
ADD tools ./tools
ADD shared ./shared
ADD test ./test
```

3. Run '...'
4. See error...

**Environment Information**
- Operating System: Windows
- Docker Version: v20.10.23 - Compose version 
- Node version: 16.19.0
- Testcontainers version: 9.1.3
