### ISSUE TITLE
How can I use a synonyms text file with test containers

### ISSUE THREAD

**Issue by vitaminsofsalem** [testcontainers/testcontainers-node#594]
Hi,

I want to use a custom synonyms txt file in the volume of the docker container used for elastic search. I can do it locally by putting the following in the `docker-compose.yaml` file:

```
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./synonyms.txt
        target: /usr/share/elasticsearch/config/synonyms.txt
```

But I can't find how to do something similar in test containers in the documentation.
