### ISSUE TITLE
NodeJS Client - new DockerComposeEnvironment results in "build contains unsupported option: 'secrets'"

### ISSUE THREAD

**Issue by anton-prehendo** [testcontainers/testcontainers-node#690]
**Expected Behaviour**
`DockerComposeEnvironment` should support compose v2 where `secrets` are allowed under `build`. E.g. 

```
version: '3.8'
services:
  server:
    container_name: server
    command: npm run start:debug
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules:consistent
    build:
      context: .
      target: development
      secrets:
        - npmrc
```

**Actual Behaviour**

Right now the above fails with 
```
Error: Jest: Got error running globalSetup - /home/runner/work/server/test/service/setup.ts, reason: The Compose file './docker-compose.yaml' is invalid because:
services.server.build contains unsupported option: 'secrets'
```

Locally running `docker compose up --build` works fine and `secrets` being under `build` is supported. It seems like testcontainers aren't supporting compose v2 in the node js client?

**Testcontainer Logs**
N/A

**Steps to Reproduce**
See description above

**Environment Information**
- Operating System: `Mac Air m2`
- Docker Version: `Docker version 24.0.2, build cb74dfc`
- Node version: `v18.17.0`
- Testcontainers version: `"testcontainers": "^10.3.2",`
