### ISSUE TITLE
dynamodb-local inside Gitlab CI

### ISSUE THREAD

**Issue by Meemaw** [testcontainers/testcontainers-node#7]
I can't get [amazon/dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local/) image work inside Gitlab CI. Note that it works locally without any problems. I haven't tried if this works in [testcontainers-java](https://github.com/testcontainers/testcontainers-java), cc @rnorth

I'm using CI settings from [docs](https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/).

My `.gitlab-ci.yml`:

```yml
image: node:12

stages:
  - prepare
  - test

# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_DRIVER: overlay2

install_packages_run_linters:
  stage: prepare
  script:
    - yarn install
    - yarn lint
  artifacts:
    expire_in: 1 hour
    paths:
      - ./node_modules

test:unit:
  stage: test
  script:
    - DEBUG=testcontainers yarn test --runInBand --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  dependencies:
    - install_packages_run_linters
```

I'm setting up container like this:

```typescript
const startedContainer = new GenericContainer("amazon/dynamodb-local").withExposedPorts(8000).start()
```

Relevant CI output:

````
[0KRunning with gitlab-runner 11.11.0-rc2 (7f58b1ec)
[0;m[0K  on docker-auto-scale 0277ea0f
[0;msection_start:1557296045:prepare_executor
[0K[0KUsing Docker executor with image node:12 ...
[0;m[0KStarting service docker:dind ...
[0;m[0KPulling docker image docker:dind ...
[0;m[0KUsing docker image sha256:6204caf6c5927058f10fab0e4661b5f7a37d9a986a89b28a176a9958a0a5b7d3 for docker:dind ...
[0;m[0KWaiting for services to be up and running...
[0;m[0KPulling docker image node:12 ...
[0;m[0KUsing docker image sha256:c77f0d290562eefd2c9e5481cc1707f40a43d2dd5f7719384bd3b8f05699ffd7 for node:12 ...
[0;msection_end:1557296093:prepare_executor
[0Ksection_start:1557296093:prepare_script
[0KRunning on runner-0277ea0f-project-12215658-concurrent-0 via runner-0277ea0f-srm-1557295996-5afcffc7...
section_end:1557296098:prepare_script
[0Ksection_start:1557296098:get_sources
[0KInitialized empty Git repository in /builds/Meemaw/meshwatch-backend-core/.git/
[32;1mFetching changes...[0;m
[32;1mCreated fresh repository.[0;m
From https://gitlab.com/Meemaw/meshwatch-backend-core
 * [new branch]      master     -> origin/master
[32;1mChecking out fb1e6645 as master...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1557296100:get_sources
[0Ksection_start:1557296100:restore_cache
[0Ksection_end:1557296101:restore_cache
[0Ksection_start:1557296101:download_artifacts
[0K[32;1mDownloading artifacts for install_packages_run_linters (208940828)...[0;m
Downloading artifacts from coordinator... ok      [0;m  id[0;m=208940828 responseStatus[0;m=200 OK token[0;m=oi_pU5bU
section_end:1557296112:download_artifacts
[0Ksection_start:1557296112:build_script
[0K[32;1m$ DEBUG=testcontainers yarn test --runInBand --coverage[0;m
yarn run v1.15.2
warning package.json: No license field
$ tsdx test --verbose --runInBand --coverage
2019-05-08T06:15:26.975Z testcontainers Pulling image: amazon/dynamodb-local:latest
2019-05-08T06:15:44.045Z testcontainers Creating container for image: amazon/dynamodb-local:latest
2019-05-08T06:15:44.875Z testcontainers Starting container with ID: 32d5a7fed1d39799e6093fa46c52e8901156043e3b1bdf2bedd937d486133ff9
2019-05-08T06:15:46.372Z testcontainers Waiting for host port :39113
2019-05-08T06:15:46.376Z testcontainers Waiting for internal port :8000
FAIL test/monitoring-service.spec.ts (72.17s)
  MonitoringService
    with DynamoStorage
      bookmarkMonitor
        âœ• should_bookmarkMonitor_when_monitorIdPassed (14ms)
        âœ• should_return404_when_bookmarkMonitorWithRandomId
      deleteMonitor
        âœ• should_deleteMonitor__when_newlyCreatedMonitorParamsPassed (1ms)
        âœ• should_return404_when_deleteMonitorWithRandomId
      getMonitorsByScheduler
        âœ• should_getEmptyCollection_when_searchByRandomScheduler (1ms)
        âœ• should_getMonitors_when_searchByTestScheduler
      getMonitors
        âœ• should_getEmptyCollection_when_searchByRandomUserId
        âœ• should_getTestMonitors_when_searchByTestUserId (1ms)
      createMonitor
        âœ• should_createNewMonitor_when_createMonitorPayloadPassed
        âœ• should_returnBoomWithFieldError_when_invalidCreateMonitorPayloadPassed
        âœ• should_returnBoomWithFieldErrors_when_emptyObjectPassed (1ms)
      updateMonitor
        âœ• should_updateMonitor_when_updateMonitorPayloadIsPassed
        âœ• should_returnBoomWithFieldError_when_createMonitorPayloadPassed (1ms)

  â— MonitoringService â€º with DynamoStorage â€º bookmarkMonitor â€º should_bookmarkMonitor_when_monitorIdPassed

    Port :39113 not bound after 40000ms
```
