### ISSUE TITLE
Multiple container networks

### ISSUE THREAD

**Issue by LiamLamb** [testcontainers/testcontainers-node#847]
Hi 👋

I am experimenting with this project to use it as part of our test infrastructure with Playwright. So far, it's working well and has significantly helped us simplify our orchestration layer!

Is there any way for us to add a container to multiple networks? 
In compose terms, I am thinking of something like this:

```yaml
networks:
  network-a:
  network-b:

services:
  mssql:
    networks:
      network-a:
        aliases:
          - alias-mssql-a

  service-a:
    networks:
      network-a:
        aliases:
          - alias-service-a
      network-b:
        aliases:
          - alias-service-a

  service-b:
    networks:
      network-b:
        aliases:
          - alias-service-b
```

The reason for this is that we only want to start `mssql` once for all test suites, and an instance of `service-a` and `service-b` per test. 
The idea is that all instances of `service-a` will be connected to the `mssql` network, and each `service-b` will be connected to its current `service-a`'s network. 

Keen to get your thoughts on this 🙂
